version: "3.9"

services:
  db:
    image: postgres:16
    container_name: devtrackr-db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: devtrackr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d devtrackr"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
