"""Add category field to tasks

Revision ID: 598d0a354503
Revises: 05a2837a075d
Create Date: 2025-08-30 14:43:25.556417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "598d0a354503"
down_revision: Union[str, Sequence[str], None] = "05a2837a075d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("category", sa.String(length=100), nullable=True))
    op.create_index("ix_tasks_category", "tasks", ["category"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_category", table_name="tasks")
    op.drop_column("tasks", "category")
    # ### end Alembic commands ###
